using System.Text.Json;
using System.Text.Json.Nodes;
using Parley.Hub;

namespace Parley.Mcp;

/// <summary>The MCP tool surface over <see cref="CollabHub"/>, executed on behalf of one named session.</summary>
internal static class CollabTools
{
    public const int MaxReadTimeoutMs = 300_000;

    /// <summary>Names the hub made up because the client never said who it is.</summary>
    public static bool IsAutoGeneratedName(string session) => session.StartsWith("session-", StringComparison.Ordinal);

    public static List<ToolDefinition> List(bool includeSetSessionName)
    {
        var tools = new List<ToolDefinition>();
        if (includeSetSessionName)
        {
            tools.Add(Tool("set_session_name",
                "IMPORTANT: Call this first before using any other collab tools. Use your project folder name as the session name (e.g., if your cwd is /workspace/Api, use 'Api'). This identifies your session to other collaborators. Also pass working_dir for reliable matching.",
                ["name"],
                ("name", "string", "Session name — use the project/folder name from your working directory (e.g., 'Api', 'cronos', 'frontend')"),
                ("working_dir", "string", "Working directory of this session (optional, helps match to project)"),
                ("project_name", "string", "Project/folder name (optional, derived from working_dir if not set)")));
        }

        tools.Add(Tool("subscribe",
            "Join a topic (creates it if it doesn't exist). Idempotent — safe to call multiple times. Once subscribed, new messages on the topic are pushed to you when your client supports channels. Also use to set/update a topic's description.",
            ["topic"],
            ("topic", "string", "Topic name (e.g., 'user-api')"),
            ("description", "string", "Optional topic description (sets or updates)")));
        tools.Add(Tool("unsubscribe",
            "Leave a topic. If you're the last subscriber, the topic and its messages are automatically deleted.",
            ["topic"],
            ("topic", "string", "Topic name to leave")));
        tools.Add(Tool("list_topics",
            "List all collaboration topics with their subscribers and message counts, plus the sessions currently connected.",
            []));
        tools.Add(Tool("send_message",
            "Send a message to a topic. Auto-creates the topic and subscribes you if needed — just send. Every other subscriber receives it.",
            ["topic", "content"],
            ("topic", "string", "Topic to send to (auto-created if needed)"),
            ("content", "string", "Message content")));
        tools.Add(Tool("read_messages",
            "Read messages from a topic (auto-subscribes you). Returns messages after the given cursor. Use for history, or to wait for a reply when pushed messages aren't arriving.",
            ["topic"],
            ("topic", "string", "Topic to read from (auto-created if needed)"),
            ("since_id", "integer", "Read messages after this ID (cursor). Omit or 0 for all."),
            ("timeout", "integer", $"Max ms to wait for a new message (0 = return immediately, max {MaxReadTimeoutMs}).")));
        return tools;
    }

    /// <param name="rename">Invoked by set_session_name with the new name, so the caller can re-key its identity.</param>
    public static async Task<CallToolResult> CallAsync(
        CollabHub hub, string session, string tool, JsonElement args, Action<string> rename, CancellationToken ct)
    {
        CallToolResult result;
        try
        {
            result = tool switch
            {
                "set_session_name" => SetSessionName(hub, session, args, rename),
                "subscribe" => Subscribe(hub, session, args),
                "unsubscribe" => Unsubscribe(hub, session, args),
                "list_topics" => ListTopics(hub),
                "send_message" => SendMessage(hub, session, args),
                "read_messages" => await ReadMessagesAsync(hub, session, args, ct),
                _ => CallToolResult.Error($"Unknown tool: {tool}"),
            };
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            return CallToolResult.Error($"Internal error: {ex.Message}");
        }

        // Unread hints ride on every successful call so a polling agent notices other topics too.
        if (!result.IsError)
        {
            var name = tool == "set_session_name" ? GetString(args, "name") ?? session : session;
            var hints = hub.GetUnreadCounts(name).Select(kv => $"[You have {kv.Value} unread message(s) on topic '{kv.Key}']").ToList();
            if (hints.Count > 0) result.Content[^1].Text += "\n\n" + string.Join("\n", hints);
        }
        return result;
    }

    private static CallToolResult SetSessionName(CollabHub hub, string session, JsonElement args, Action<string> rename)
    {
        var name = GetString(args, "name");
        if (string.IsNullOrEmpty(name)) return CallToolResult.Error("Missing required parameter: name");

        hub.RenameSession(session, name);
        hub.EnsureSession(name, GetString(args, "working_dir"), GetString(args, "project_name"));
        rename(name);
        return CallToolResult.Text($"Session renamed to '{name}'. Other sessions will see you as '{name}'.");
    }

    private static CallToolResult Subscribe(CollabHub hub, string session, JsonElement args)
    {
        var topic = GetString(args, "topic");
        if (string.IsNullOrEmpty(topic)) return CallToolResult.Error("Missing required parameter: topic");
        hub.Subscribe(session, topic, GetString(args, "description"));
        return CallToolResult.Text($"Subscribed to topic '{topic}'.");
    }

    private static CallToolResult Unsubscribe(CollabHub hub, string session, JsonElement args)
    {
        var topic = GetString(args, "topic");
        if (string.IsNullOrEmpty(topic)) return CallToolResult.Error("Missing required parameter: topic");
        var (ok, error) = hub.Unsubscribe(session, topic);
        return ok ? CallToolResult.Text($"Unsubscribed from topic '{topic}'.") : CallToolResult.Error(error!);
    }

    private static CallToolResult ListTopics(CollabHub hub)
    {
        var topics = hub.GetTopics();
        var text = topics.Count == 0
            ? "No topics exist yet."
            : string.Join("\n", topics.Select(t =>
            {
                var desc = string.IsNullOrEmpty(t.Description) ? "" : $" - {t.Description}";
                return $"- {t.Name}{desc} ({t.MessageCount} msgs, subscribers: {string.Join(", ", t.Subscribers)})";
            }));

        var live = hub.GetSessions().Where(s => s.Listeners > 0).Select(s => s.Name).ToList();
        if (live.Count > 0) text += $"\n\nConnected (receive pushes): {string.Join(", ", live)}";
        return CallToolResult.Text(text);
    }

    private static CallToolResult SendMessage(CollabHub hub, string session, JsonElement args)
    {
        var topic = GetString(args, "topic");
        if (string.IsNullOrEmpty(topic)) return CallToolResult.Error("Missing required parameter: topic");
        var content = GetString(args, "content");
        if (string.IsNullOrEmpty(content)) return CallToolResult.Error("Missing required parameter: content");

        var msg = hub.SendMessage(session, topic, content);
        return CallToolResult.Text($"Message #{msg.Id} sent to topic '{topic}'.");
    }

    private static async Task<CallToolResult> ReadMessagesAsync(CollabHub hub, string session, JsonElement args, CancellationToken ct)
    {
        var topic = GetString(args, "topic");
        if (string.IsNullOrEmpty(topic)) return CallToolResult.Error("Missing required parameter: topic");

        var timeout = Math.Clamp(GetInt(args, "timeout"), 0, MaxReadTimeoutMs);
        var (messages, cursor) = await hub.ReadMessagesAsync(session, topic, GetInt(args, "since_id"), timeout, ct);
        if (messages.Count == 0)
            return CallToolResult.Text($"No new messages on topic '{topic}'. (cursor: {cursor})");

        var lines = messages.Select(m => $"[{m.CreatedAt.ToLocalTime():HH:mm:ss}] {m.Sender}: {m.Content}");
        return CallToolResult.Text($"{messages.Count} message(s) on '{topic}':\n\n{string.Join("\n", lines)}\n\n(cursor: {cursor})");
    }

    private static ToolDefinition Tool(string name, string description, string[] required,
        params (string name, string type, string description)[] props)
    {
        var properties = new JsonObject();
        foreach (var p in props)
            properties[p.name] = new JsonObject { ["type"] = p.type, ["description"] = p.description };

        var schema = new JsonObject { ["type"] = "object", ["properties"] = properties };
        if (required.Length > 0)
            schema["required"] = new JsonArray(required.Select(r => (JsonNode)r).ToArray());
        return new ToolDefinition { Name = name, Description = description, InputSchema = schema };
    }

    private static string? GetString(JsonElement args, string name) =>
        args.ValueKind == JsonValueKind.Object && args.TryGetProperty(name, out var p) && p.ValueKind == JsonValueKind.String
            ? p.GetString()
            : null;

    private static int GetInt(JsonElement args, string name)
    {
        if (args.ValueKind != JsonValueKind.Object || !args.TryGetProperty(name, out var p)) return 0;
        if (p.ValueKind == JsonValueKind.Number && p.TryGetInt32(out var n)) return n;
        return p.ValueKind == JsonValueKind.String && int.TryParse(p.GetString(), out var s) ? s : 0;
    }
}
