using System.Text.Json;
using Parley.Hub;

namespace Parley.Mcp;

/// <summary>
/// MCP over Streamable HTTP (JSON responses, no server stream) for clients that connect to the hub
/// directly — Codex, or Claude Code without the stdio shim.
///
/// Who is calling: an <c>X-Session</c> header names the session outright (the stdio shim always
/// sends one). Otherwise <c>initialize</c> derives a name from the client's roots — or makes up
/// <c>session-N</c>, which unlocks the set_session_name tool — and hands back an
/// <c>Mcp-Session-Id</c> that must accompany every later request. An unknown id (the hub restarted)
/// gets a 404, which tells a spec-following client to initialize again.
/// </summary>
public sealed class HttpMcpEndpoint(CollabHub hub)
{
    private const string Instructions =
        "Parley lets you coordinate with other AI coding sessions through pub/sub topics. Topics and subscriptions are automatic: send_message and read_messages create and join topics as needed. "
        + "Every tool result lists unread messages on your topics — check them. Use read_messages with a timeout to wait for a reply.";

    private readonly object _lock = new();
    private readonly Dictionary<string, string> _sessionNames = new(); // Mcp-Session-Id → name
    private int _nextAutoSessionId;

    public sealed record Result(int StatusCode, string? Body, string? McpSessionId);

    public async Task<Result> HandleAsync(string body, string? sessionHeader, string? mcpSessionId,
        string? workingDirHeader, CancellationToken ct)
    {
        JsonRpcRequest? request;
        try
        {
            request = JsonSerializer.Deserialize<JsonRpcRequest>(body, Json.Options);
        }
        catch (JsonException)
        {
            return new Result(400, Json.Serialize(JsonRpcResponse.Fail(null, -32700, "Parse error")), null);
        }
        if (request?.Method is null)
            return new Result(400, Json.Serialize(JsonRpcResponse.Fail(request?.Id, -32600, "Invalid request")), null);

        string session;
        string? issuedId = null;
        if (!string.IsNullOrWhiteSpace(sessionHeader))
        {
            session = sessionHeader.Trim();
        }
        else if (request.Method == "initialize")
        {
            var dir = RootDirectory(request.Params) ?? workingDirHeader;
            lock (_lock)
            {
                session = dir != null ? FolderName(dir) : $"session-{++_nextAutoSessionId}";
                issuedId = Guid.NewGuid().ToString("N")[..16];
                _sessionNames[issuedId] = session;
            }
            workingDirHeader = dir;
        }
        else if (string.IsNullOrEmpty(mcpSessionId))
        {
            return new Result(400, Json.Serialize(JsonRpcResponse.Fail(request.Id, -32600,
                "Missing Mcp-Session-Id (or X-Session) header")), null);
        }
        else
        {
            lock (_lock)
            {
                if (!_sessionNames.TryGetValue(mcpSessionId, out session!))
                    return new Result(404, Json.Serialize(JsonRpcResponse.Fail(request.Id, -32001,
                        "Unknown session — re-initialize")), null);
            }
            issuedId = mcpSessionId;
        }

        hub.EnsureSession(session, workingDirHeader);

        if (request.IsNotification)
            return new Result(202, null, issuedId);

        var response = request.Method switch
        {
            "initialize" => JsonRpcResponse.Success(request.Id, new
            {
                protocolVersion = Protocol.Negotiate(request.Params),
                capabilities = new { tools = new { listChanged = false } },
                serverInfo = new { name = "parley", version = Protocol.Version },
                instructions = Instructions,
            }),
            "ping" => JsonRpcResponse.Success(request.Id, new { }),
            "tools/list" => JsonRpcResponse.Success(request.Id,
                new { tools = CollabTools.List(includeSetSessionName: CollabTools.IsAutoGeneratedName(session)) }),
            "tools/call" => await CallToolAsync(request, session, mcpSessionId ?? issuedId, ct),
            _ => JsonRpcResponse.Fail(request.Id, -32601, $"Method not found: {request.Method}"),
        };
        return new Result(200, Json.Serialize(response), issuedId);
    }

    private async Task<JsonRpcResponse> CallToolAsync(JsonRpcRequest request, string session, string? mcpSessionId, CancellationToken ct)
    {
        if (request.Params is not { ValueKind: JsonValueKind.Object } p
            || !p.TryGetProperty("name", out var nameEl) || nameEl.ValueKind != JsonValueKind.String)
            return JsonRpcResponse.Fail(request.Id, -32602, "Invalid params: expected 'name' and optional 'arguments'");

        var args = p.TryGetProperty("arguments", out var a) ? a : default;
        var result = await CollabTools.CallAsync(hub, session, nameEl.GetString()!, args, newName =>
        {
            if (mcpSessionId == null) return;
            lock (_lock) _sessionNames[mcpSessionId] = newName;
        }, ct);
        return JsonRpcResponse.Success(request.Id, result);
    }

    /// <summary>First file root (or VS Code workspace folder) from initialize params, as a local path.</summary>
    internal static string? RootDirectory(JsonElement? initializeParams)
    {
        if (initializeParams is not { ValueKind: JsonValueKind.Object } p) return null;
        foreach (var key in new[] { "roots", "workspaceFolders" })
        {
            if (!p.TryGetProperty(key, out var list) || list.ValueKind != JsonValueKind.Array) continue;
            foreach (var item in list.EnumerateArray())
            {
                var raw = item.ValueKind == JsonValueKind.String ? item.GetString()
                    : item.ValueKind == JsonValueKind.Object && item.TryGetProperty("uri", out var u) && u.ValueKind == JsonValueKind.String ? u.GetString()
                    : null;
                if (string.IsNullOrEmpty(raw)) continue;
                var path = Uri.TryCreate(raw, UriKind.Absolute, out var uri) && uri.IsFile ? uri.LocalPath : raw;
                path = path.TrimEnd('/', '\\');
                if (path.Length > 0) return path;
            }
        }
        return null;
    }

    internal static string FolderName(string path)
    {
        var p = path.Replace('\\', '/').TrimEnd('/');
        var i = p.LastIndexOf('/');
        var name = (i >= 0 ? p[(i + 1)..] : p).TrimEnd(':');
        return name.Length > 0 ? name : "root";
    }
}
